search:
  keywords:
    - "ciro"
    - "endeksi"
  match_mode: "any"     # any | all
  headless: true        # true | false
  max_bulten: 50        # kaç bülten içinde arama yapılacak (performans için)
  max_clicks: 120       # her bülten sayfasında kaç tıklama denensin

inputs:
  bulten_list_path: "config/bulten.yaml"
