bulten_pages:
- https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Agustos-2025-53923
- https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Ekim-2025-53919
- https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Eylul-2025-53918
