bulten_pages:
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Agustos-2023-49581
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Agustos-2024-53722
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Agustos-2025-54126
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Aralik-2023-53725
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Aralik-2024-54133
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Ekim-2023-49587
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Ekim-2024-53724
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Ekim-2025-54128
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Eylul-2023-49582
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Eylul-2024-53723
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Eylul-2025-54127
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Haziran-2023-49579
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Haziran-2024-53720
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Haziran-2025-54132
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Kasim-2023-49583
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Kasim-2024-54129
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Mart-2024-53717
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Mart-2025-54123
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Mayis-2024-53719
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Mayis-2025-54124
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Nisan-2024-53718
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Nisan-2025-54131
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Ocak-2024-53715
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Ocak-2025-54122
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Subat-2024-53716
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Subat-2025-54130
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Temmuz-2023-49580
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Temmuz-2024-53721
- https://data.tuik.gov.tr/Bulten/Index?p=Ciro-Endeksleri-Temmuz-2025-54125
- https://data.tuik.gov.tr/Bulten/Index?p=Girisim-Ozelliklerine-Gore-Uluslararasi-Hizmet-Ticareti-Istatistikleri-2021-53442
- https://data.tuik.gov.tr/Bulten/Index?p=Girisim-Ozelliklerine-Gore-Uluslararasi-Hizmet-Ticareti-Istatistikleri-2022-53847
- https://data.tuik.gov.tr/Bulten/Index?p=Girisimcilik-ve-Is-Demografisi-2022-49391
- https://data.tuik.gov.tr/Bulten/Index?p=Girisimcilik-ve-Is-Demografisi-2023-53452
- https://data.tuik.gov.tr/Bulten/Index?p=Girisimcilik-ve-Is-Demografisi-2024-54058
- https://data.tuik.gov.tr/Bulten/Index?p=Kucuk-ve-Orta-Buyuklukteki-Girisim-Istatistikleri-2022-49438
- https://data.tuik.gov.tr/Bulten/Index?p=Kucuk-ve-Orta-Buyuklukteki-Girisim-Istatistikleri-2023-53543
- https://data.tuik.gov.tr/Bulten/Index?p=Kucuk-ve-Orta-Buyuklukteki-Girisim-Istatistikleri-2024-54054
- https://data.tuik.gov.tr/Bulten/Index?p=Perakende-Satis-Endeksleri-Agustos-2023-49612
- https://data.tuik.gov.tr/Bulten/Index?p=Perakende-Satis-Endeksleri-Eylul-2023-49613
- https://data.tuik.gov.tr/Bulten/Index?p=Perakende-Satis-Endeksleri-Temmuz-2023-49618
- https://data.tuik.gov.tr/Bulten/Index?p=Sektor-Bilancolari-2022-49677
- https://data.tuik.gov.tr/Bulten/Index?p=Yabanci-Kontrollu-Girisim-Istatistikleri-2021-49762
- https://data.tuik.gov.tr/Bulten/Index?p=Yabanci-Kontrollu-Girisim-Istatistikleri-2022-53804
- https://data.tuik.gov.tr/Bulten/Index?p=Yabanci-Kontrollu-Girisim-Istatistikleri-2023-54190
- https://data.tuik.gov.tr/Bulten/Index?p=Yillik-Sanayi-ve-Hizmet-Istatistikleri-2022-49569
- https://data.tuik.gov.tr/Bulten/Index?p=Yillik-Sanayi-ve-Hizmet-Istatistikleri-2023-53782
- https://data.tuik.gov.tr/Bulten/Index?p=Yillik-Sanayi-ve-Hizmet-Istatistikleri-2024-54051
- https://data.tuik.gov.tr/Bulten/Index?p=Yillik-Sanayi-ve-Hizmet-Istatistikleri-Yatirim-Harcamalari-2023-57933
- https://data.tuik.gov.tr/Bulten/Index?p=Yurt-Disinda-Kontrol-Edilen-Girisim-Istatistikleri-2022-53443
- https://data.tuik.gov.tr/Bulten/Index?p=Yurt-Disinda-Kontrol-Edilen-Girisim-Istatistikleri-2023-54164
