categories_pages:
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Adalet-ve-Secim-110
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Bilim,-Teknoloji-ve-Bilgi-Toplumu-102
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Cevre-ve-Enerji-103
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Dis-Ticaret-104
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Egitim,-Kultur,-Spor-ve-Turizm-105
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Ekonomik-Guven-117
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Enflasyon-ve-Fiyat-106
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Gelir,-Yasam,-Tuketim-ve-Yoksulluk-107
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Insaat-ve-Konut-116
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Istihdam,-Issizlik-ve-Ucret-108
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Nufus-ve-Demografi-109
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Saglik-ve-Sosyal-Koruma-101
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Sanayi-114
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Tarim-111
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Ticaret-ve-Hizmet-115
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Ulastirma-ve-Haberlesme-112
- https://data.tuik.gov.tr/Kategori/GetKategori?p=Ulusal-Hesaplar-113
