source_bulten_yaml: config/bulten.yaml
downloads:
- bulten_url: https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Agustos-2025-53923
  download_links:
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=1Xsh6kRV9GZ90wBDclFVo8Sq0FzrPSFpKef6lflqcPZUemXm7xfVSztj3Ao4pGD7
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=2IbdXoU9XadXeoxIfx4LrnnKFb8E1jrF4huwvD6XrTX5VGQxoSCWQyLygY2bEl19
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=CxsqyNIHN3TecgTE87mKIGK6EUCOO606XsIK9dhTzL3MSRyPEneCvHo5EbsQhQ5/
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=GmnFh2y7UlKEJ4NrPI6F9QzabSQ25ukarCFzog9Rkz5ljoX2Epiod9l0czBG50F1
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=hlskFYL6y4OhUYfybXAn0VjN6YjT62mw8oiiLuii1ZaHFoihMRqSQNQUqRYEzQrL
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=oTD7B8giD0TvbAy1SgPH48n0OZaykqIA2SS2shrk7/20bZq283faYK/GiyWX7tzh
- bulten_url: https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Ekim-2025-53919
  download_links:
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=3Mz95fYCvzD9PT8IQQmhdAOzWLNQCx5HZRViMLQrdtcoZAR0BDe32KfqcdxSPzoC
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=7nn7U6yQ08VcA0WqjsA2lox3Pztu7wVmP1cG9cjCBJLmxp3CM/sJLihQQJNLwdGX
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=DbOy6P4RmOWs8d82CycdrDtFKFmDKTQQtvLQSi2EWNnKQJKNIQ3d6tolOaOR1Oi1
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=H3BJ9SD42vm2g/CFVe83YIkRcvQkO82i9UAJrCRqeb6hJ04AmGRZnbp3yrSpd0pw
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=M6ga7yOip9cKKV3DIrlFPOZlJcFTHR3xDUmWKPN3TdpNE62abKUaDA9JFt0KjIXt
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=MjNVONFpenO3JUEDKikPvzlM/bX4Ej5LDtd8ceLpa5e0WlscjMIM03rjr0fh5TJ2
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=SChtbScCUFEGq4yQ6WpuqAlpuY0tNZytlq9Y0v4gRkevy8sve9gVUq4DqlK2LlJ9
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=bL9KN2VzBRyoHltSrAS8MObm3R61CCBV5zKQ9bCfeaKO2nuJOfBSNDWzDW8VLf9N
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=mWK/cd5kOzsHg8jAWPS1E/MWOWiFB3uPxq4959bOldFJntVgsBMtXGfLNEoM8jVp
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=omqexsfDaXywPuyRfaabUYC8GgpJgSNTHieHiuWRCZ2ZpKWHt0z3Q2grmoM47Pzk
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=rG1hzrxvdkVtyPMfVNCvvO8DIRKFZtIv3zBUm8xODpTDSSHFIuRi353VbanQxjf/
- bulten_url: https://data.tuik.gov.tr/Bulten/Index?p=Dis-Ticaret-Endeksleri-Eylul-2025-53918
  download_links:
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=7DpYp81AL5cwHCQZgO/8wwhSHYLXpgAeIDaBW1khndNhA2DCORfk95dpOBQfvwDu
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=84jI8Hhrg5oAKUSkn8jRY25o08AzNpdvJGAWFjBXtCoGsv7StR80Vh9GvEVOAoUo
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=DCUeL3tqIUq7ZINW/OKVvx70B1uS2vzs04UFaT9/ja2BJ0KtzmhiOgluaOYDmXV8
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=K/snmm25WBouu64BIMu2oxqcGAmvMz8LwGLXtWhGSlnf6vuvLMS4rhA1tVT6ZPK7
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=KuRk9BbmaLaoku2kQL5Jy80voussamLFXc1CSpKsEqKBGgoOMLVnNgeVhP8tHeFD
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=Lf/Nj8Lp/v5WDm5JqChjfZutH4HxcFLfjZWnDNoqZlZmJG8UyUw0fn0gKwukl4Bu
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=RcYf4xnnMSqX31fMVc1QrH6NOBT2e5OmcR/znHwMtTLRRsFm07hZyHKSra50Raz3
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=d228eSuRsUWyeYy/p0304UQMKaeqsR6oCCPxBuiz9kmSyrE8EUm4QbrfuE0fdgL5
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=hUNtTyw5bzuwKsRDnB3Qs0SAyDSzIRrcgiv0JCFSOS6vNMQ9gui5t6LojG8dSiKb
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=qjdCOcd7RTJNC/b/AyG/lDA4rqgMeswInmWydoNsmtp3u9woHzeT7ek981zqpMnS
  - https://data.tuik.gov.tr/Bulten/DownloadIstatistikselTablo?p=u2uNybFtAnG0lXaP4Lkh43fRMsoEyyPAdy1eHZKa0lvMX43WeH87LfDR3URXYw0t
